version: '3.8'
services:
  react-app:
    build:
      context: ./crypto-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Maps Nginx's port 80 to localhost:3000
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Maps server port 5000
    environment:
      - CMC_API_KEY=your-api-key # Pass environment variables
    restart: always
